First background
PAHFIT/pahfit pull request #105
Opened 2021-03-15 20:04 UTC by jdtsmith

Initial draft of background info

2021-03-15 23:43 UTC, karllark commented on docs/background.rst
> +``PAHFIT`` was developed in 2004-2006 as part of the Spitzer IRS Nearby Galaxy Survey (SINGS) to aid in the analysis of Spitzer/InfraRed Spectrograph (IRS) resolved spectral mapping of nearby galaxie
Spitzer *Infrared* Nearby Galaxy Survey.  ;-)

2021-03-16 13:01 UTC, karllark commented
Ready for review?  Did a quick read and it looks great!

2021-03-17 21:48 UTC, jdtsmith commented
> Ready for review? Did a quick read and it looks great!

Yep

2021-03-18 12:49 UTC, karllark commented on docs/background.rst
> +``PAHFIT`` was developed in 2004-2006 as part of the Spitzer Infrared Nearby Galaxy Survey (SINGS) to aid in the analysis of Spitzer/InfraRed Spectrograph (IRS) resolved spectral mapping of nearby ga
The last sentence seems to be missing an ending.

2021-03-18 12:50 UTC, karllark requested changes
Looks good.  Just one comment that needs addressing.

2021-03-18 13:30 UTC, karllark approved these changes
Looks great!

2021-03-18 13:30 UTC, karllark commented
Ready to merge?

2021-03-18 15:18 UTC, merged