function to return model compounds
PAHFIT/pahfit pull request #156
Opened 2021-11-16 02:00 UTC by els1

Added function to helpers.py to return the model compounds: total continuum, total dust continuum, total dust features, total H2 lines.

2021-11-16 02:16 UTC, els1 commented
Issue #19: IDL version gives (in addition to individual components)

TOTAL_DUST_CONTINUUM=dc_tot, TOTAL_CONTINUUM=tot_cont,                         TOTAL_DUST_FEATURES=df_tot, LINES=lines,TOTAL_LINES=lines_tot, $
EXTINCTION_CURVE=ext_curve

I didn't add:
total lines, only total H2 lines
extinction curve

Should this be added?

2021-11-16 14:40 UTC, karllark commented
The codacy failure is minor and is due to trailing white space on some lines.  This is a PEP8 thing.  It can be left or fixed if you want.  Click on the Details link and and then the view more details to see the specific lines that have this issue.

2021-11-16 14:45 UTC, karllark commented
I think you should add a compound that is the atomic emission lines at a minimum (currently this code returns the H2 only).  

I would return the attenuation curve as well.  Useful as in the future we will have a more complex attenuation curve (e.g., ices with the v2.1 AKARI version).

2021-11-17 02:20 UTC, els1 commented
> The codacy failure is minor and is due to trailing white space on some lines. This is a PEP8 thing. It can be left or fixed if you want. Click on the Details link and and then the view more details to see the specific lines that have this issue.

Thanks. I think I removed them.

2021-11-22 18:46 UTC, karllark approved these changes
Looks good to me.

2021-11-22 18:47 UTC, karllark commented
One thought.  It would be good to have some documentation on this useful function.  Like a doc page that shows the output for our standard M101 nuclear fit.  This could be part of this PR.  But doesn't have to be.  If not, then an issue should be opened so that such docs are added at some point.

2021-11-22 19:01 UTC, els1 commented
> One thought. It would be good to have some documentation on this useful function. Like a doc page that shows the output for our standard M101 nuclear fit. This could be part of this PR. But doesn't have to be. If not, then an issue should be opened so that such docs are added at some point.

I will work on including the docs in this PR.

2021-11-22 19:33 UTC, ThomasSYLai requested changes
Everything looks good to me except adding "calculate_compounds" in __all__

2021-11-22 19:33 UTC, ThomasSYLai commented on pahfit/helpers.py
>  __all__ = ["read_spectrum", "initialize_model", "fit_spectrum"]
add "calculate_compounds" in __all__

2021-11-22 20:02 UTC, els1 commented on pahfit/helpers.py
>  __all__ = ["read_spectrum", "initialize_model", "fit_spectrum"]
corrected. thanks.

2021-11-22 20:47 UTC, ThomasSYLai approved these changes

2021-11-29 23:49 UTC, els1 commented
I will add the docs in a new PR as there is an active PR on docs.

2021-11-30 16:21 UTC, karllark commented
So, is this PR ready for merging @els1?

2021-11-30 21:03 UTC, els1 commented
@karllark yes it is.

2021-12-02 09:06 UTC, merged