Yaml documentation
PAHFIT/pahfit pull request #213
Opened 2022-06-13 20:00 UTC by Dhruvil2911

2022-06-21 00:06 UTC, jdtsmith commented
Thanks for working on this.  I think it's OK to merge as is and improve later.  There is a lot of info pertinent info missing from the Wiki text I wrote.  Probably good to have a high level format with a pointer to the Wiki (which we can reorganize to make it more "permanent"). I'd also suggest therefore dropping the full example, as that's in the Wiki.  I can also clean that up and check that in so we get versioning on it; it's in org not rst, but most people will read online anyway and won't know the difference I guess.

2022-06-27 21:55 UTC, els1 requested changes
Overall looks good. Some minor comments.

2022-07-01 01:54 UTC, Dhruvil2911 commented on docs/file_formats.rst
> +          '[SIII]_18': 18.713
Fixed the error.

2022-07-28 18:34 UTC, els1 approved these changes

2022-07-28 19:30 UTC, els1 approved these changes

2022-07-28 21:22 UTC, els1 requested changes
I think your last commit included the changes of your other PR. Could you update this PR so you only commit changes related to the Yaml documentation?

2022-07-28 21:55 UTC, Dhruvil2911 commented
Yeah I've reset the PR just to the changes in the documentation.

2022-07-28 23:24 UTC, els1 approved these changes

2022-10-04 14:45 UTC, jdtsmith commented
@drvdputt can you take a look at this and see if it may be useful for your documentation efforts?

2022-10-04 15:22 UTC, drvdputt commented
I have a placeholder "YAML format description here" in my documentation (on the same page). So yes, some parts of this will be useful, even if a bit outdated. There will be a merge conflict, but since it's only documentation, a bad merge won't break anything. I can just reorganize the different parts.

2022-10-04 15:30 UTC, merged