Area Gauss/Drude
PAHFIT/pahfit pull request #225
Opened 2022-07-18 22:32 UTC by Dhruvil2911

In this PR, I've used area (power) as the parameter instead of the amplitude to fit Gaussian and Drude profiles.
I've made 2 classes AreaGaussian and AreaDrude in the component_models file corresponding to each profile.
There are corresponding changes in the helpers, base, and feature_strength files. I have also created an ipac file with the area columns (scipack_ExGal_area_1.ipac).
The command > run_pahfit M101_Nucleus_irs.ipac scipack_ExGal_area_1.ipac 
will demonstrate the changes.

For feature_strengths of Gaussian/Drude, I have simply equated it to the area (power).

2022-07-19 12:10 UTC, karllark commented on pahfit/base.py
> +#from astropy.modeling.functional_models import Gaussian1D
Please delete if we are no longer going to use.

2022-07-19 12:14 UTC, karllark requested changes
Great to see this PR.

2022-07-19 12:14 UTC, karllark commented on pahfit/base.py
> +#from astropy.modeling.physical_models import Drude1D
Please delete if we are no longer going to use.

2022-07-19 12:14 UTC, karllark commented on pahfit/base.py
> +#from astropy.modeling.functional_models import Gaussian1D
Please delete if we are no longer going to use.

2022-07-19 12:14 UTC, karllark commented on pahfit/component_models.py
> +
Please add a docstring to provide basic information about this function.  Like what currently exists for `S07_attenuation` for example.

2022-07-19 12:14 UTC, karllark commented on pahfit/component_models.py
> +
Docstring please.

2022-07-19 12:16 UTC, karllark commented
Is the idea here to have pahfit only do line fitting based on area?  Or are we going to still allow central intensity?  If the former, then this PR is in good shape.  If the latter, then significant changes needed to support both.

The tests are failing as they are based on fitting the central intensity of lines.  This can be changes to use areas instead, but need to know the answer to my above queries to know the direction to go.

2022-07-21 18:10 UTC, Dhruvil2911 commented
Thanks for reviewing the PR Karl. I've made the requested changes and added the docstring. Let me know if any other changes are required.

2022-07-24 13:24 UTC, karllark commented
> Is the idea here to have pahfit only do line fitting based on area? Or are we going to still allow central intensity? If the former, then this PR is in good shape. If the latter, then significant changes needed to support both.
> 
> The tests are failing as they are based on fitting the central intensity of lines. This can be changes to use areas instead, but need to know the answer to my above queries to know the direction to go.

Any response to this query?  @jdtsmith @els1

2022-07-24 23:48 UTC, jdtsmith commented
The new model will use power exclusively for lines and dust features.  So it’s a good idea IMO to get the current astropy model to as well.  I think @Ameek-Sidhu plans to just use amplitude for now as a stopgap.

2022-07-25 15:23 UTC, jdtsmith commented
> > The new model will use power exclusively for lines and dust features. So it’s a good idea IMO to get the current astropy model to as well. I think @Ameek-Sidhu plans to just use amplitude for now as a stopgap.
> 
> To be clear, this means we should change the tests to use power instead of amplitude, right? (Checking as I don't understand the "astropy model" in this context.) If so, this should be done in this PR and then all future work has to be done in power. I provide guidance on how to do this.

Yes, once implemented.  Actually all the tests need some attention I think (haven't looked closely at them).

2022-07-25 15:31 UTC, karllark commented
> Actually all the tests need some attention I think (haven't looked closely at them).

Tests always need more.  But they are working at this point until this change is made.  Hence the tests can be updated as part of this PR.  Then once it is merged, the tests will continue to work and do what we want - check that nothing has broken the core functionality.

2022-07-25 16:48 UTC, jdtsmith commented
Maybe my impressions are wrong but I've been getting test failure emails for months.  With apologies for my contributions to the increased entropy, I'm happy for any additional commits/PRs that help with the testing situation.  I'll leave this one to you and @Dhruvil2911; but ideally this PR would go in after @Ameek-Sidhu and @drvdputt get YAML-hookup + API cleanup.

2022-07-25 16:54 UTC, karllark commented
Briefly, the tests passed.  See https://github.com/PAHFIT/pahfit/actions.  ;-)  Takes vigilance to keep them passing.  BTW, I turned off email notification of failing tests long, long ago.  Just too many!

2022-07-25 16:55 UTC, karllark commented
Note that the tests are currently failing due to codestyle issues.  We have quite a suite of tests to make sure all parts of the repository work including the code, docs, codestyle, etc.

2022-12-13 21:19 UTC, jdtsmith commented
@karllark  @alexmaragko @drvdputt Do we intend to follow through with this?  No matter what happens with the new model, it seems smart to have an astropy.modeling version "along for the ride" for testing (and as a backup).  For that to work "for real", we need a power-based Gaussian and Drude.  Right now we are _lying_ and pretending amplitude = power.

2022-12-14 20:26 UTC, karllark commented
Yes this can be done fairly easily.

2022-12-14 22:29 UTC, jdtsmith commented
Great thanks @karllark ; would appreciate checking and cleaning up this PR (or generating a new one).  I believe we're close to merging the dev branch, so it could happen after that.   Then at least we could do our power-based fits.

2023-03-03 16:40 UTC, jdtsmith commented
We need to clarify the astropy-flavored pahfit model's _internal units_ to complete this.  This is TBD until dev merge.

2024-07-26 20:13 UTC, jdtsmith commented
This has been superseded by #295, continue conversation there.

2024-07-26 20:13 UTC, closed without merging